# fly.toml app configuration file generated for slackbot-project-iu6tsq on 2026-05-24T23:20:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slackbot-project-iu6tsq'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 80

[checks]
  [checks.health]
    port = 3000
    type = 'http'
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
